### ISSUE TITLE
Ridgeback collision failed

### ISSUE THREAD

**Issue by chenxing618** [ridgeback/ridgeback#50]
I added the collision in urdf, but the robot arm can also go through the top and chassis link. Could you show us how to fix that?

Many thanks for that

**Comment by civerachb-cpr** [comment]
What model of arm did you add to the URDF?  Can you share your modified URDF so we can take a look?

**Comment by chenxing618** [comment]
The modifed urdf is to add a panda arm on the platform. 

![image](https://user-images.githubusercontent.com/58518677/169162148-cb96f987-a38b-4ff6-b962-0f38a06b8842.png)



The connect part is as followed:

  
  <link name="mid_mount" />
  
  <joint name="mid_mount_joint" type="fixed">
    <parent link="base_link" />
    <child link="mid_mount" />
    <origin xyz="0 0 0.28" rpy="0 0 0"/>
  </joint>




  
  
  <joint name="connection_fixed" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.28"/>
    <parent link="base_link"/>
    <child link="panda_link0"/>
  </joint>






  

  
  <link name="panda_link0">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.05"/>
       <mass value="2.9"/>
       <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://meshes/collision/link0.obj"/>
      </geometry>
      <material name="panda_white">
    		<color rgba="1. 1. 1. 1."/>
  		</material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://meshes/collision/link0.obj"/>
      </geometry>
      <material name="panda_white"/>
    </collision>
  </link>

**Comment by chenxing618** [comment]
<link name="mid_mount" />
  
  <joint name="mid_mount_joint" type="fixed">
    <parent link="base_link" />
    <child link="mid_mount" />
    <origin xyz="0 0 0.28" rpy="0 0 0"/>
  </joint>




  
  
  <joint name="connection_fixed" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.28"/>
    <parent link="base_link"/>
    <child link="panda_link0"/>
  </joint>






  

  
  <link name="panda_link0">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.05"/>
       <mass value="2.9"/>
       <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://meshes/collision/link0.obj"/>
      </geometry>
      <material name="panda_white">
    		<color rgba="1. 1. 1. 1."/>
  		</material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://meshes/collision/link0.obj"/>
      </geometry>
      <material name="panda_white"/>
    </collision>
  </link>

**Comment by chenxing618** [comment]
![image](https://user-images.githubusercontent.com/58518677/169162388-84516832-3041-45c6-be76-75155f001b99.png)

**Comment by chenxing618** [comment]
But it seems that it will go through the top and chassis link. AND i checked that there is the collision in your original urdf by using stl file. While it also go through

**Comment by chenxing618** [comment]
https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/gym/pybullet_data/franka_panda

The above is the panda arm urdf.

**Comment by civerachb-cpr** [comment]
Does your `panda_link0` actually have a collision tag?  The screenshot you shared cuts off at the closing `</visual>` tag but doesn't show a `collision` tag as part of the link.  Instead of sharing a screenshot of your URDF file can you share the actual file so we can see the whole thing?

For adding a Franka arm to the Ridgeback we have a separate `ridgeback_manipulation` package here: https://github.com/ridgeback/ridgeback_manipulation

With that package you can add the Franka arm to the robot using:
```
source $(catkin_find ridgeback_franka_description scripts/setup_ridgeback_panda_envar --first-only)
roslaunch ridgeback_viz view_model.launch
```

The visual model:
![ridgeback-panda](https://user-images.githubusercontent.com/59611394/169163161-f6e55fdd-000d-428b-af0a-2d9c15b7eed3.png)

The collision model:
![ridgeback-panda-collision](https://user-images.githubusercontent.com/59611394/169163242-65bfd539-90ea-41fa-9a20-e0fee08138fe.png)

EDIT
It's also worth pointing out that in Rviz it's possible to use the `joint_state_publisher_gui` package to move the arm into an invalid state; Rviz does not respect the robot's collision bodies, as it's just a visualizer, not a physics simulation.  For example:
![self-collision](https://user-images.githubusercontent.com/59611394/169163830-1af60974-c6e3-4c09-a02f-9476db9153e7.png)

If you are simulating the robot in Gazebo then the arm inside the simulation should not clip through the robot, as Gazebo will use the collision meshes in its physics simulation.  Similarly MoveIt will use the collision meshes when planning and executing trajectories to make sure the robot does not enter an invalid state.

Regarding simulation however, we cannot offer a lot of support simulating a mobile arm on the robot; we rely on third-party packages for the arms, some of which do not offer good support for Gazebo.  The Ridgeback base-platform works in Gazebo, but we cannot guarantee that any given third-party arm will.

**Comment by chenxing618** [comment]
Many thanks for you kind response. The panda_link0 has the collision. I did not cut it in that. I will upload the file. Please help me to find some reasons.

**Comment by chenxing618** [comment]
[panda_ridgeback.zip](https://github.com/ridgeback/ridgeback/files/8721210/panda_ridgeback.zip)

**Comment by chenxing618** [comment]
Okay. I see. it is because we do not use the physical machine. Many thanks for your kind response.

**Comment by chenxing618** [comment]
Could you also view the urdf that I build. Cause I use the Pybullet Engine. And it shows the same results like the above.

**Comment by chenxing618** [comment]
[panda_ridgeback.zip](https://github.com/ridgeback/ridgeback/files/8721223/panda_ridgeback.zip)

**Comment by civerachb-cpr** [comment]
I'm afraid I'm not familiar with Pybullet, so I can't offer much advice on specific issues that may relate to that.
One thing I would suggest though would be that instead of adding the Ridgeback links to Pybullet's Panda robot URDF, would be to do something like the `ridgeback_manipulation` package I linked above where we use the `RIDGEBACK_URDF_EXTRAS` envar to include the arm directly in the official Ridgeback URDF file.

**Comment by chenxing618** [comment]
Many thanks for your kind response. I will follow your advice.
