### ISSUE TITLE
ROS Noetic?

### ISSUE THREAD

**Issue by Quest2GM** [ridgeback/ridgeback#55]
Hi,

Is there a plan to support ROS Noetic for the Ridgeback for Gazebo?

Thanks

**Comment by tonybaltovski** [comment]
Yes, the source is here: https://github.com/ridgeback/ridgeback_simulator or it can be installed from binaries using `sudo apt install ros-noetic-ridgeback-simulator`.

**Comment by Quest2GM** [comment]
Why don't the common packages for the ridgeback have a noetic branch on github (ie. navigation, control, description)?

**Comment by civerachb-cpr** [comment]
The `melodic-devel` branch is compatible with Noetic; because no changes were needed between ROS releases it's common-practice to re-use the existing branch rather than create a new one.

The OSRF `rosdistro` repo uses the `melodic-devel` branch for building the Noetic packages: https://github.com/ros/rosdistro/blob/master/noetic/distribution.yaml#L8537
